### ISSUE TITLE
Trim spaces in org names and fix org dropdown issue

### ISSUE THREAD

**Issue by ecurrencyhodler** [stakwork/sphinx-tribes#1339]
**Describe the bug**
Bounties aren't displaying if you are signed in.

https://github.com/stakwork/sphinx-tribes/assets/32662508/1b85c308-9aa8-46c9-9487-1de956e8d4aa

However if you are NOT signed in you can view the bounty. 

**Expected behavior**
I should be able to view the bounty if I am signed in.

**Desktop (please complete the following information):**
 - Browser: Chrome

### Acceptance Criteria
- [ ] I have tested on Chrome desktop
- [ ] I have posted a video

**Comment by aliraza556** [comment]
@ecurrencyhodler can you assign me?

**Comment by ecurrencyhodler** [comment]
This is a fairly complex issue. I think someone from our team needs to take a look.

**Comment by ecurrencyhodler** [comment]
https://github.com/stakwork/sphinx-tribes/assets/32662508/d5bc1b68-a12d-4d5f-bd67-01954a62c286

@kevkevinpal  @elraphty Some logs from console.

**Comment by wright-eric** [comment]
2 issues found in this
1. The extra spaces at the beginning or end are not handled by the [toCapitalize](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/helpers/helpers-extended.ts#L271) function here resulting in panic and hence the white screen. 

2. The function [getUserDropdownOrganizations](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/store/main.ts#L1869) update the current organizations in main store. This function is called on two occasion.
a. When  we load the page we fetch current user organization.
b. When we visit other users profile, it loads their organization. 
This should not be stored as [dropdownOrganization](https://github.com/stakwork/sphinx-tribes/blob/master/frontend/app/src/store/main.ts#L1841) because when i would then try to create new bounty it would show the other user organizations in dropdown 
![image](https://github.com/stakwork/sphinx-tribes/assets/93755484/8fdc1608-f07e-4fd4-aa5c-8b6f7e1aa05c)

**Comment by elraphty** [comment]
@wright-eric the `dropdownOrganization` should display the organizations a user is an admin to or has a manage bounty role, this error is coming from line 178 in `https://github.com/stakwork/sphinx-tribes/blob/7ee0aeabf84ec77442b8ea8ab70be3259fd8abce/frontend/app/src/people/widgetViews/OrganizationView.tsx` the dropdown query should only be called with `uiStore.meInfo?.id`which is the logged in user, making this change will fix the error.

**Comment by ecurrencyhodler** [comment]
@wright-eric I can create a bounty for you for addressing these two issues.

**Comment by ecurrencyhodler** [comment]
https://community.sphinx.chat/bounty/1208

**Comment by ecurrencyhodler** [comment]
Hey @wright-eric or @elraphty would this PR affect the bounty creation modal? It looks like some of the UI elements got altered.
<img width="1005" alt="Screenshot 2024-01-22 at 8 41 39 AM" src="https://github.com/stakwork/sphinx-tribes/assets/32662508/e6cb616e-ea2f-4f89-8f60-ee8d5aa143e5">

**Comment by wright-eric** [comment]
@ecurrencyhodler  i dont think it should as there were no UI changes. What do you think @elraphty  ?
