### ISSUE TITLE
Data model to store your profile info

### ISSUE THREAD

**Issue by soup20** [stakwork/sphinx-tribes#290]
We need profile pages in three places: the Sphinx people page, the App, and in each tribe a user is a part of. Here is a table of what we currently have in each of those places:

|| People Page | App | Tribe Specific |
| -------------- | ----- | ----- | ----- |
| profile picture |y|y|y|
| username |y|y|y|
| pubkey |y|y||
| bio |y|||
| price to connect |y|||
| twitter handle |y|||
| github handle |y|||
| linkedin handle* ||||
| keyword (programming languages) |y|||
| github repositories |y|||
| tribes owned |y|||
| total sats contributed* ||||
| total sats earned* ||||
| badges |y|||
|admin?||||
|last active||||
|reputation score||||
|date joined||||
|referral link||||

We want to store all this info so that the user can choose what they wish to display.

**Comment by Evanfeenstra** [comment]
- Most of the data is inside the `people` table, in the `extras` JSONB column
- `badges` data is inside `sphinx-elements` server

In order to pull data from the people DB, we would need the user's pubkey to be included in tribe messages. So we can add a new field "original_pubkey" inside the `MessageContent` https://github.com/stakwork/sphinx-relay/blob/master/src/network/interfaces.ts#L4.

How do we want to handle that though? Should the user choose if their pubkey is included? Or the tribe admin chooses for a tribe? @omoniyi24 @pitoi @soup20

**Comment by Evanfeenstra** [comment]
Other options:

- share `people_id` instead of pubkey. And make a route on the people page to pull data with the id, not the pubkey.

- share everything. pubkeys are meant to be public. Instead of privacy, focus on pseudonimity: burner pubkeys, you can join a tribe with a different pubkey anyway.

**Comment by omoniyi24** [comment]
I have a few questions:

1. Is there a page or an endpoint for users to configure what they’re willing to display on tribes?
2. Will the new people server endpoint return user details along with the tribes they belong to and their respective configs? (I believe that querying with the hostId, i.e., Postgre ID, and the tribe Id may help to streamline the information returned.)

**Comment by Evanfeenstra** [comment]
@tobi-bams We decided we do not need filters per-user AND per-tribe. So the new `profile_filters` column is all we need

**Comment by tobi-bams** [comment]
> @tobi-bams We decided we do not need filters per-user AND per-tribe. So the new `profile_filters` column is all we need

Alright, thanks @Evanfeenstra
